In [1]:
import numpy as np
a = np.random.randn(3, 4)  # 直接传入维度
print(a)


[[-0.70187814  0.03466943  0.26243251 -0.55139735]
 [ 1.36789377 -0.36153155 -2.08122004  0.35038373]
 [ 1.6845157   0.17637811 -1.75921951  0.12587443]]


In [2]:
import numpy as np
np.random.seed(64)
a = np.random.randn(5, 6)  # 直接传入维度
b = np.random.randn(5, 3)
print(a)
print(b)
c = np.concatenate([a, b], axis=1)
print(c)


[[ 1.10032294 -1.98262742 -1.15024951  2.19291636 -1.90143503 -0.43389669]
 [-1.13558187 -1.03329507 -2.37195862  0.70333809  0.38484212  1.7504858 ]
 [-1.19506926  0.29512768  0.04832088 -0.17129885 -0.50502703 -1.36851403]
 [-0.10257869 -0.38657733 -0.45610576 -1.35917171 -0.39687699  0.59463191]
 [-1.37793369  0.51179504 -0.54133239 -0.49094076  0.32615422  0.73867359]]
[[-0.13003621 -0.03350093 -1.34988964]
 [-1.02619022 -1.87639537 -1.35834067]
 [ 1.85728363  1.70499395 -1.37052023]
 [ 0.6752157  -0.37460609 -0.54231276]
 [ 0.97005336  0.76693399 -0.92581152]]
[[ 1.10032294 -1.98262742 -1.15024951  2.19291636 -1.90143503 -0.43389669
  -0.13003621 -0.03350093 -1.34988964]
 [-1.13558187 -1.03329507 -2.37195862  0.70333809  0.38484212  1.7504858
  -1.02619022 -1.87639537 -1.35834067]
 [-1.19506926  0.29512768  0.04832088 -0.17129885 -0.50502703 -1.36851403
   1.85728363  1.70499395 -1.37052023]
 [-0.10257869 -0.38657733 -0.45610576 -1.35917171 -0.39687699  0.59463191
   0.6752157  -0

In [6]:
b = np.array([[2,3],[3,4]])
c  = np.array([[2,3],[3,4]])
a = np.concatenate([b,c],axis = 1)
a

array([[2, 3, 2, 3],
       [3, 4, 3, 4]])

In [14]:
import numpy as np
np.random.seed(64)
a = np.random.randint(-11, 11, size=(2, 4))  # 生成一个 5x6 的数组，值在 0 到 10 之间
b = np.random.randint(-11, 11, size=(2, 3))  # 生成一个 5x3 的数组，值在 0 到 10 之间
c = np.concatenate([a,b],axis=1)
d = np.random.randint(0, 20, size=(2, 1))  #
obj = np.random.randint(-10, 10, size=(7, 1))  
print(a)
print(b)
print(c)
print(d)
print(obj)

[[-7 -5 -5  6]
 [ 9  8 10  5]]
[[-1 -3 -9]
 [ 5  6 -7]]
[[-7 -5 -5  6 -1 -3 -9]
 [ 9  8 10  5  5  6 -7]]
[[2]
 [6]]
[[  5]
 [  2]
 [  4]
 [-10]
 [  0]
 [ -5]
 [  4]]


In [18]:
obj[0].item()

5

In [62]:
import numpy as np
import gurobipy as gp

def create_max(obj,c,d):
    model = gp.Model("linear_programming_example")

    # 添加决策变量，假设每个变量是连续的
    x = model.addVars(c.shape[1], lb=0, name="x")  # 7 个决策变量

    # 设置目标函数
    model.setObjective(gp.quicksum(obj[i].item() * x[i] for i in range(c.shape[1])), GRB.MAXIMIZE)

    # 添加约束 Ax <= b
    # 假设 c = [a, b] 被视为约束矩阵，而 d 是对应的右侧值
    for i in range(c.shape[0]):
        model.addConstr(gp.quicksum(c[i, j] * x[j] for j in range(c.shape[1])) <= d[i], name=f"constraint_{i}")

    # 求解模型
    model.optimize()

    # 输出结果
    if model.status == GRB.OPTIMAL:
        print("\nOptimal Solution:")
        for v in model.getVars():
            print(f"{v.varName}: {v.x}")
    else:
        print("No optimal solution found")


In [63]:
import numpy as np
import gurobipy as gp

def create_dual(obj,c,d):
    model = gp.Model("linear_programming_example")

    # 添加决策变量，假设每个变量是连续的
    x = model.addVars(c.shape[1], lb=0, name="x")  # 7 个决策变量

    # 设置目标函数
    model.setObjective(gp.quicksum(obj[i].item() * x[i] for i in range(c.shape[1])), GRB.MINIMIZE)

    # 添加约束 Ax <= b
    # 假设 c = [a, b] 被视为约束矩阵，而 d 是对应的右侧值
    for i in range(c.shape[0]):
        model.addConstr(gp.quicksum(c[i, j] * x[j] for j in range(c.shape[1])) >= d[i], name=f"constraint_{i}")

    # 求解模型
    model.optimize()

    # 输出结果
    if model.status == GRB.OPTIMAL:
        print("\nOptimal Solution:")
        for v in model.getVars():
            print(f"{v.varName}: {v.x}")
    else:
        print("No optimal solution found")


In [64]:
import numpy as np
import gurobipy as gp
from gurobipy import GRB

# 设置随机数种子
np.random.seed(64)

# 随机生成数据
a = np.random.randint(0, 11, size=(3, 4))  # 2x4 矩阵
b = np.random.randint(0, 11, size=(3, 3))  # 2x3 矩阵
c = np.concatenate([a,b],axis=1)  # 2x7 矩阵，水平连接
d = np.random.randint(0, 20, size=(3, 1))  # 2x1 矩阵（右边的约束值）
obj = np.random.randint(0, 10, size=(7, 1))  # 7x1 矩阵（目标函数的系数）
create_max(obj=obj,c=c,d=d)

Gurobi Optimizer version 10.0.2 build v10.0.2rc0 (win64)

CPU model: 13th Gen Intel(R) Core(TM) i7-13700HX, instruction set [SSE2|AVX|AVX2]
Thread count: 16 physical cores, 24 logical processors, using up to 24 threads

Optimize a model with 3 rows, 7 columns and 19 nonzeros
Model fingerprint: 0x7513e3e4
Coefficient statistics:
  Matrix range     [1e+00, 1e+01]
  Objective range  [2e+00, 9e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+01, 2e+01]
Presolve removed 0 rows and 1 columns
Presolve time: 0.00s
Presolved: 3 rows, 6 columns, 16 nonzeros

Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    1.9285714e+01   5.865357e-01   0.000000e+00      0s
       3    1.8041667e+01   0.000000e+00   0.000000e+00      0s

Solved in 3 iterations and 0.00 seconds (0.00 work units)
Optimal objective  1.804166667e+01

Optimal Solution:
x[0]: 0.0
x[1]: 0.4583333333333333
x[2]: 1.75
x[3]: 0.0
x[4]: 0.0
x[5]: 0.0
x[6]: 0.0


In [65]:
import numpy as np
import gurobipy as gp
from gurobipy import GRB

# 设置随机数种子
np.random.seed(64)

# 随机生成数据
a = np.random.randint(0, 11, size=(3, 4))  # 2x4 矩阵
b = np.random.randint(0, 11, size=(3, 3))  # 2x3 矩阵
c = np.concatenate([a,b],axis=1)  # 2x7 矩阵，水平连接
d = np.random.randint(0, 20, size=(3, 1))  # 2x1 矩阵（右边的约束值）
obj = np.random.randint(0, 10, size=(7, 1))  # 7x1 矩阵（目标函数的系数）
create_dual(obj=d,c = c.T,d = obj)

Gurobi Optimizer version 10.0.2 build v10.0.2rc0 (win64)

CPU model: 13th Gen Intel(R) Core(TM) i7-13700HX, instruction set [SSE2|AVX|AVX2]
Thread count: 16 physical cores, 24 logical processors, using up to 24 threads

Optimize a model with 7 rows, 3 columns and 19 nonzeros
Model fingerprint: 0xc765208d
Coefficient statistics:
  Matrix range     [1e+00, 1e+01]
  Objective range  [1e+01, 2e+01]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e+00, 9e+00]
Presolve removed 1 rows and 0 columns
Presolve time: 0.00s
Presolved: 6 rows, 3 columns, 16 nonzeros

Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    0.0000000e+00   4.000000e+00   0.000000e+00      0s
       2    1.8041667e+01   0.000000e+00   0.000000e+00      0s

Solved in 2 iterations and 0.00 seconds (0.00 work units)
Optimal objective  1.804166667e+01

Optimal Solution:
x[0]: 0.8333333333333334
x[1]: 0.0
x[2]: 0.39583333333333326


In [66]:
import numpy as np
import gurobipy as gp
from gurobipy import GRB

create_max(obj=obj[:4],c=a,d=d)

Gurobi Optimizer version 10.0.2 build v10.0.2rc0 (win64)

CPU model: 13th Gen Intel(R) Core(TM) i7-13700HX, instruction set [SSE2|AVX|AVX2]
Thread count: 16 physical cores, 24 logical processors, using up to 24 threads

Optimize a model with 3 rows, 4 columns and 11 nonzeros
Model fingerprint: 0x8f9f392b
Coefficient statistics:
  Matrix range     [1e+00, 1e+01]
  Objective range  [5e+00, 9e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+01, 2e+01]
Presolve removed 0 rows and 1 columns
Presolve time: 0.00s
Presolved: 3 rows, 3 columns, 8 nonzeros

Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    1.9285714e+01   5.865357e-01   0.000000e+00      0s
       3    1.8041667e+01   0.000000e+00   0.000000e+00      0s

Solved in 3 iterations and 0.01 seconds (0.00 work units)
Optimal objective  1.804166667e+01

Optimal Solution:
x[0]: 0.0
x[1]: 0.4583333333333333
x[2]: 1.75
x[3]: 0.0


In [67]:
import numpy as np
import gurobipy as gp
from gurobipy import GRB

create_max(obj=obj[4:],c=b,d=d)

Gurobi Optimizer version 10.0.2 build v10.0.2rc0 (win64)

CPU model: 13th Gen Intel(R) Core(TM) i7-13700HX, instruction set [SSE2|AVX|AVX2]
Thread count: 16 physical cores, 24 logical processors, using up to 24 threads

Optimize a model with 3 rows, 3 columns and 8 nonzeros
Model fingerprint: 0x4d68d777
Coefficient statistics:
  Matrix range     [1e+00, 8e+00]
  Objective range  [2e+00, 6e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+01, 2e+01]
Presolve time: 0.00s
Presolved: 3 rows, 3 columns, 8 nonzeros

Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    1.0000000e+31   4.750000e+30   1.000000e+01      0s
       3    1.1800000e+01   0.000000e+00   0.000000e+00      0s

Solved in 3 iterations and 0.00 seconds (0.00 work units)
Optimal objective  1.180000000e+01

Optimal Solution:
x[0]: 0.0
x[1]: 1.6
x[2]: 1.1


In [ ]:
import numpy as np
import gurobipy as gp
from gurobipy import GRB

# 设置随机数种子
np.random.seed(64)

# 随机生成数据
a = np.random.randint(0, 11, size=(3, 4))  # 2x4 矩阵
b = np.random.randint(0, 11, size=(3, 3))  # 2x3 矩阵
c = np.concatenate([a,b],axis=1)  # 2x7 矩阵，水平连接
d = np.random.randint(0, 20, size=(3, 1))  # 2x1 矩阵（右边的约束值）
obj = np.random.randint(0, 10, size=(7, 1))  # 7x1 矩阵（目标函数的系数）

# 打印生成的随机矩阵
print("Matrix A:")
print(a)
print("Matrix B:")
print(b)
print("Matrix C (Concatenated):")
print(c)
print("Matrix D:")
print(d)
print("Objective Coefficients:")
print(obj)

# 创建优化模型
model = gp.Model("linear_programming_example")

# 添加决策变量，假设每个变量是连续的
x = model.addVars(7, lb=0, name="x")  # 7 个决策变量

# 设置目标函数
model.setObjective(gp.quicksum(obj[i].item() * x[i] for i in range(7)), GRB.MAXIMIZE)

# 添加约束 Ax <= b
# 假设 c = [a, b] 被视为约束矩阵，而 d 是对应的右侧值
for i in range(2):
    model.addConstr(gp.quicksum(c[i, j] * x[j] for j in range(7)) <= d[i], name=f"constraint_{i}")

# 求解模型
model.optimize()

# 输出结果
if model.status == GRB.OPTIMAL:
    print("\nOptimal Solution:")
    for v in model.getVars():
        print(f"{v.varName}: {v.x}")
else:
    print("No optimal solution found")


In [ ]:
from gurobipy import Model, GRB

# Initialize model
model = Model("PrimalProblem")

# Variables
x1 = model.addVar(lb=0, name="x1")
x2 = model.addVar(lb=0, name="x2")

# Parameters
c1, c2 = 1, 2
a11, a12, b1 = 1, 2, 4
a21, a22, b2 = 3, 1, 6

# Objective: Minimize c1 * x1 + c2 * x2
model.setObjective(c1 * x1 + c2 * x2, GRB.MINIMIZE)

# Constraints
model.addConstr(a11 * x1 + a12 * x2 >= b1, "c1")
model.addConstr(a21 * x1 + a22 * x2 <= b2, "c2")

# Solve
model.optimize()

# Display results
if model.status == GRB.OPTIMAL:
    print("Optimal Primal Solution:")
    for v in model.getVars():
        print(f"{v.varName} = {v.x}")
    print(f"Optimal Objective Value (z) = {model.objVal}")


Gurobi Optimizer version 10.0.2 build v10.0.2rc0 (win64)

CPU model: 13th Gen Intel(R) Core(TM) i7-13700HX, instruction set [SSE2|AVX|AVX2]
Thread count: 16 physical cores, 24 logical processors, using up to 24 threads

Optimize a model with 2 rows, 2 columns and 4 nonzeros
Model fingerprint: 0x1fb96878
Coefficient statistics:
  Matrix range     [1e+00, 3e+00]
  Objective range  [1e+00, 2e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [4e+00, 6e+00]
Presolve time: 0.01s
Presolved: 2 rows, 2 columns, 4 nonzeros

Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    0.0000000e+00   2.000000e+00   0.000000e+00      0s
       1    4.0000000e+00   0.000000e+00   0.000000e+00      0s

Solved in 1 iterations and 0.02 seconds (0.00 work units)
Optimal objective  4.000000000e+00
Optimal Primal Solution:
x1 = 0.0
x2 = 2.0
Optimal Objective Value (z) = 4.0


In [ ]:
# 提取对偶变量值
if model.status == GRB.OPTIMAL:
    print("\nDual Values (Shadow Prices):")
    for constr in model.getConstrs():
        print(f"{constr.ConstrName}: Dual Value = {constr.Pi}")

    print("\nReduced Costs:")
    for var in model.getVars():
        print(f"{var.varName}: Reduced Cost = {var.RC}")



Dual Values (Shadow Prices):
c1: Dual Value = 1.0
c2: Dual Value = 0.0

Reduced Costs:
x1: Reduced Cost = 0.0
x2: Reduced Cost = 0.0


In [ ]:
# Dual Model
dual_model = Model("DualProblem")

# Variables (dual variables for constraints in primal)
y1 = dual_model.addVar(lb=0, name="y1")
y2 = dual_model.addVar(lb=0, name="y2")

# Objective: Maximize b1 * y1 + b2 * y2
dual_model.setObjective(b1 * y1 + b2 * y2, GRB.MAXIMIZE)

# Dual constraints
dual_model.addConstr(a11 * y1 + a21 * y2 <= c1, "dc1")
dual_model.addConstr(a12 * y1 + a22 * y2 <= c2, "dc2")

# Solve
dual_model.optimize()

# Display results
if dual_model.status == GRB.OPTIMAL:
    print("Optimal Dual Solution:")
    for v in dual_model.getVars():
        print(f"{v.varName} = {v.x}")
    print(f"Optimal Objective Value (w) = {dual_model.objVal}")


Gurobi Optimizer version 10.0.2 build v10.0.2rc0 (win64)

CPU model: 13th Gen Intel(R) Core(TM) i7-13700HX, instruction set [SSE2|AVX|AVX2]
Thread count: 16 physical cores, 24 logical processors, using up to 24 threads

Optimize a model with 2 rows, 2 columns and 4 nonzeros
Model fingerprint: 0xe959ba4b
Coefficient statistics:
  Matrix range     [1e+00, 3e+00]
  Objective range  [4e+00, 6e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 2e+00]
Presolve time: 0.00s
Presolved: 2 rows, 2 columns, 4 nonzeros

Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    1.0000000e+31   2.500000e+30   1.000000e+01      0s
       2    4.0000000e+00   0.000000e+00   0.000000e+00      0s

Solved in 2 iterations and 0.01 seconds (0.00 work units)
Optimal objective  4.000000000e+00
Optimal Dual Solution:
y1 = 1.0
y2 = 0.0
Optimal Objective Value (w) = 4.0
